version: 4
shared:
  environment:
    NODE_ENV: test
  settings:
    email:
      addresses:
        - junaid.hussain@yahooinc.com
      statuses:
        - SUCESS
        - FAILURE
  annotations:
    screwdriver.cd/cpu: LOW
    screwdriver.cd/ram: LOW
jobs:
  main:
    requires:
      - ~pr
      - ~commit
    steps:
      - run:
          commands:
            - chmod +x ./my_script.sh
            - ./my_script.sh
